Transiently set channel info in build
This info will not be tracked in the repo. Will fix some merge conflicts and a race condition between setupenv and agent builds.

diff --git a/scripts/build.yml b/scripts/build.yml
--- a/scripts/build.yml
+++ b/scripts/build.yml
@@ -29,16 +29,20 @@ steps:
 
   - bash: npm run prebuild
     displayName: "prebuild"
-  - bash: |
-      pkgchannel=$(node -p "require('./scripts/getver.js').default('channel')")
-      if [[ ("$(channel)" != "${pkgchannel}") && ("${BUILD_REASON}" != "PullRequest")]]
-      then
-        (1>&2 echo ERROR: Channel information in package.json does not match pipeline:)
-        (1>&2 echo ERROR: Channel in package.json = \"${pkgchannel}\" while pipeline channel = \"$(channel)\" )
-      fi
-    failOnStderr: true
-    condition: ne('$(Build.Reason)', 'PullRequest')
-    displayName: "Validate channel info"
+  # - bash: |
+  #     pkgchannel=$(node -p "require('./scripts/getver.js').default('channel')")
+  #     if [[ ("$(channel)" != "${pkgchannel}") && ("${BUILD_REASON}" != "PullRequest")]]
+  #     then
+  #       (1>&2 echo ERROR: Channel information in package.json does not match pipeline:)
+  #       (1>&2 echo ERROR: Channel in package.json = \"${pkgchannel}\" while pipeline channel = \"$(channel)\" )
+  #     fi
+  #   failOnStderr: true
+  #   condition: ne('$(Build.Reason)', 'PullRequest')
+  #   displayName: "Validate channel info"
+  - bash: | # Switch channel info if incorrect
+      chmod u+x scripts/updpackagechannel.sh
+      ./scripts/updpackagechannel.sh
+    displayName: "Switch channel info to $(channel)"
 
     # Bump transient version
   - bash: |
